version: 2.1
orbs:
  architect: giantswarm/architect@4.26.0

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push goldilocks-app chart to giantswarm-catalog"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "goldilocks-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push goldilocks-app chart to control-plane-catalog"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "goldilocks-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
