version: 2.1
orbs:
  architect: giantswarm/architect@2.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push goldilocks-app chart"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "goldilocks-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
