apiVersion: v2
appVersion: "v4.9.0"
annotations:
  application.giantswarm.io/team: turtles
version: "6.3.1"
description: |
  A Helm chart for running Fairwinds Goldilocks. See https://github.com/FairwindsOps/goldilocks
name: goldilocks
icon: https://s.giantswarm.io/app-icons/goldilocks/1/icon_light.svg
maintainers:
  - name: giantswarm/team-turtles
    email: team-turtles@giantswarm.io
sources:
  - https://github.com/FairwindsOps/goldilocks
keywords:
  - goldilocks
  - resources
  - kubernetes
dependencies:
  - name: goldilocks
    version: 7.0.2
    repository: https://charts.fairwinds.com/stable
