kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "goldilocks.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "goldilocks.name" . }}
    helm.sh/chart: {{ include "goldilocks.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: controller
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "goldilocks.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress